# sysshep.nodiskstat.sh: do monitoring when diskstat is not available, through db2 
# autogenerated Mon Dec 12 17:44:11 MST 2016 by taylor using command:
# gensh -to sysshep.nodiskstat.sh -path /opt/ublu/ublu.jar -optr u USERNAME @username ${ username }$ -optr p PASSWORD @password ${ password }$ -optr h HOST @host ${ host }$ ${ sysshep.nodiskstat.sh: do monitoring when diskstat is not available, through db2 }$ sysshep.nodiskstat.ublu ${ sysshep.nodiskstat ( @username @password @host ) }$

# Usage message
function usage { 
echo "sysshep.nodiskstat.sh: do monitoring when diskstat is not available, through db2 "
echo "This shell script was autogenerated Mon Dec 12 17:44:11 MST 2016 by taylor."
echo "Usage: $0 [silent] -h -u USERNAME -p PASSWORD -h HOST "
echo "	where"
echo "	-h		display this help message and exit 0"
echo "	-u USERNAME	username  (required option)"
echo "	-p PASSWORD	password  (required option)"
echo "	-h HOST	host  (required option)"
echo "---"
echo "If the keyword 'silent' appears ahead of all options, then included files will not echo and prompting is suppressed."
echo "Exit code is the result of execution, or 0 for -h or 2 if there is an error in processing options"
}

#Test if user wants silent includes
if [ "$1" == "silent" ]
then
	SILENT="-silent "
	shift
else
	SILENT=""
fi

# Process options
while getopts u:p:h:h the_opt
do
	case "$the_opt" in
		u)	USERNAME="$OPTARG";;
		p)	PASSWORD="$OPTARG";;
		h)	HOST="$OPTARG";;
		h)	usage;exit 0;;
		[?])	usage;exit 2;;

	esac
done
shift `expr ${OPTIND} - 1`
if [ $# -ne 0 ]
then
	echo "Superfluous argument(s) $*"
	usage
	exit 2
fi

# Translate options to tuple assignments
if [ "${USERNAME}" != "" ]
then
	gensh_runtime_opts="${gensh_runtime_opts}string -to @username -trim \${ ${USERNAME} }$ "
else
	echo "Option -u USERNAME is a required option but is not present."
	usage
	exit 2
fi
if [ "${PASSWORD}" != "" ]
then
	gensh_runtime_opts="${gensh_runtime_opts}string -to @password -trim \${ ${PASSWORD} }$ "
else
	echo "Option -p PASSWORD is a required option but is not present."
	usage
	exit 2
fi
if [ "${HOST}" != "" ]
then
	gensh_runtime_opts="${gensh_runtime_opts}string -to @host -trim \${ ${HOST} }$ "
else
	echo "Option -h HOST is a required option but is not present."
	usage
	exit 2
fi

# Invocation
java -jar /opt/ublu/ublu.jar ${gensh_runtime_opts} include ${SILENT}sysshep.nodiskstat.ublu sysshep.nodiskstat \( @username @password @host \) 
exit $?
