# sysshep.msg_matches.sh: monitors a user's message queue for a message matching a regex pattern 
# autogenerated Wed Oct 24 10:08:15 MDT 2018 by taylor using command:
# gensh -to sysshep.msg_matches.sh -path /opt/ublu/ublu.jar -includepath $SCRIPTDIR -optr p PROPERTIES @properties ${ credentials properties file }$ -opt q QUSERNAME @qusername ${ username to be monitored (defaults to QSYSOPR) }$ -optr t TIMEFILE @timefile ${ temp file to store last timestamp in }$ -optr P PATTERN @pattern ${ Regex pattern to check message bodies for. This is not a search, it must match exactly, so you will likely need to use .+ or .* at the beginning and end. }$ ${ sysshep.msg_matches.sh: monitors a user's message queue for a message matching a regex pattern }$ sysshep/msgq.ublu ${ sysshep.msg_matches ( @properties @qusername @timefile @pattern ) }$

# Usage message
function usage {
echo "sysshep.msg_matches.sh: monitors a user's message queue for a message matching a regex pattern "
echo "This shell script was autogenerated Wed Oct 24 10:08:15 MDT 2018 by taylor."
echo "Usage: $0 [silent] [-h] [-X...] [-Dprop=val] -p PROPERTIES [-q QUSERNAME] -t TIMEFILE -P PATTERN"
echo "	where"
echo "	-h		display this help message and exit 0"
echo "	-X xOpt		pass a -X option to the JVM (can be used many times)"
echo "	-D some.property=\"some value\"	pass a property to the JVM (can be used many times)"
echo "	-p PROPERTIES	credentials properties file  (required option)"
echo "	-q QUSERNAME	username to be monitored (defaults to QSYSOPR) "
echo "	-t TIMEFILE	temp file to store last timestamp in  (required option)"
echo "	-P PATTERN	Regex pattern to check message bodies for. This is not a search, it must match exactly, so you will likely need to use .+ or .* at the beginning and end.  (required option)"
echo "---"
echo "If the keyword 'silent' appears ahead of all options, then included files will not echo and prompting is suppressed."
echo "Exit code is the result of execution, or 0 for -h or 2 if there is an error in processing options"
echo "This script sets \$SCRIPTDIR to the script's directory prior to executing prelude commands and Ublu invocation."
}

#Test if user wants silent includes
if [ "$1" == "silent" ]
then
	SILENT="-silent "
	shift
else
	SILENT=""
fi

# Process options
while getopts p:q:t:P:D:X:h the_opt
do
	case "$the_opt" in
		p)	PROPERTIES="$OPTARG";;
		q)	QUSERNAME="$OPTARG";;
		t)	TIMEFILE="$OPTARG";;
		P)	PATTERN="$OPTARG";;
		h)	usage;exit 0;;
		D)	JVMPROPS="${JVMPROPS} -D${OPTARG}";;
		X)	JVMOPTS="${JVMOPTS} -X${OPTARG}";;
		[?])	usage;exit 2;;

	esac
done
shift `expr ${OPTIND} - 1`
if [ $# -ne 0 ]
then
	echo "Superfluous argument(s) $*"
	usage
	exit 2
fi

# Translate options to tuple assignments
if [ "${PROPERTIES}" != "" ]
then
	gensh_runtime_opts="${gensh_runtime_opts}string -to @properties -trim \${ ${PROPERTIES} }$ "
else
	echo "Option -p PROPERTIES is a required option but is not present."
	usage
	exit 2
fi
if [ "${QUSERNAME}" != "" ]
then
	gensh_runtime_opts="${gensh_runtime_opts}string -to @qusername -trim \${ ${QUSERNAME} }$ "
fi
if [ "${TIMEFILE}" != "" ]
then
	gensh_runtime_opts="${gensh_runtime_opts}string -to @timefile -trim \${ ${TIMEFILE} }$ "
else
	echo "Option -t TIMEFILE is a required option but is not present."
	usage
	exit 2
fi
if [ "${PATTERN}" != "" ]
then
	gensh_runtime_opts="${gensh_runtime_opts}string -to @pattern -trim \${ ${PATTERN} }$ "
else
	echo "Option -P PATTERN is a required option but is not present."
	usage
	exit 2
fi

SCRIPTDIR=$(CDPATH= cd "$(dirname "$0")" && pwd)

# Prelude commands to execute before invocation
# No prelude commands

# Invocation
java${JVMOPTS}${JVMPROPS} -Dublu.includepath="$SCRIPTDIR" -jar /opt/ublu/ublu.jar ${gensh_runtime_opts} include ${SILENT}sysshep/msgq.ublu sysshep.msg_matches \( @properties @qusername @timefile @pattern \) 
exit $?
