# sysshep.msgq.sh: print all messages for message queue since the last check 
# autogenerated Wed Feb 01 10:04:50 MST 2017 by taylor using command:
# gensh -to sysshep.msgq.sh -path /opt/ublu/ublu.jar -includepath $SCRIPTDIR -optr p PROPERTIES @properties ${ credentials properties file }$ -opt q MSGQUEUE @msgqueue ${ username to be monitored (defaults to QSYSOPR) }$ -optr t TIMEFILE @timefile ${ temp file to store last timestamp in }$ ${ sysshep.msgq.sh: print all messages for message queue since the last check }$ sysshep/msgq.ublu ${ sysshep.msgq ( @properties @msgqueue @timefile ) }$

# Usage message
function usage {
echo "sysshep.msgq.sh: print all messages for message queue since the last check "
echo "This shell script was autogenerated Wed Feb 01 10:04:50 MST 2017 by taylor."
echo "Usage: $0 [silent] -h -p PROPERTIES -q MSGQUEUE -t TIMEFILE "
echo "	where"
echo "	-h		display this help message and exit 0"
echo "	-p PROPERTIES	credentials properties file  (required option)"
echo "	-q MSGQUEUE	message queue path (defaults to /qsys.lib/qsysopr.msgq)"
echo "	-t TIMEFILE	temp file to store last timestamp in  (required option)"
echo "---"
echo "If the keyword 'silent' appears ahead of all options, then included files will not echo and prompting is suppressed."
echo "Exit code is the result of execution, or 0 for -h or 2 if there is an error in processing options"
}

#Test if user wants silent includes
if [ "$1" == "silent" ]
then
	SILENT="-silent "
	shift
else
	SILENT=""
fi

# Process options
while getopts p:q:t:h the_opt
do
	case "$the_opt" in
		p)	PROPERTIES="$OPTARG";;
		q)	MSGQUEUE="$OPTARG";;
		t)	TIMEFILE="$OPTARG";;
		h)	usage;exit 0;;
		[?])	usage;exit 2;;

	esac
done
shift `expr ${OPTIND} - 1`
if [ $# -ne 0 ]
then
	echo "Superfluous argument(s) $*"
	usage
	exit 2
fi

# Translate options to tuple assignments
if [ "${PROPERTIES}" != "" ]
then
	gensh_runtime_opts="${gensh_runtime_opts}string -to @properties -trim \${ ${PROPERTIES} }$ "
else
	echo "Option -p PROPERTIES is a required option but is not present."
	usage
	exit 2
fi
if [ "${MSGQUEUE}" != "" ]
then
	gensh_runtime_opts="${gensh_runtime_opts}string -to @msgqueue -trim \${ ${MSGQUEUE} }$ "
fi
if [ "${TIMEFILE}" != "" ]
then
	gensh_runtime_opts="${gensh_runtime_opts}string -to @timefile -trim \${ ${TIMEFILE} }$ "
else
	echo "Option -t TIMEFILE is a required option but is not present."
	usage
	exit 2
fi

SCRIPTDIR=$(CDPATH= cd "$(dirname "$0")" && pwd)

set -o noglob

# Invocation
java -Dublu.includepath="$SCRIPTDIR" -jar /opt/ublu/ublu.jar ${gensh_runtime_opts} include ${SILENT}sysshep/msgq.ublu sysshep.msgq \( @properties @msgqueue @timefile \) 
exit $?
