# sysshep.alarm_msgw.sh: monitor's a user's message queue for messages waiting 
# autogenerated Mon Dec 12 17:31:39 MST 2016 by taylor using command:
# gensh -to sysshep.alarm_msgw.sh -path /opt/ublu/ublu.jar -optr u USERNAME @username ${ login username }$ -optr p PASSWORD @password ${ login password }$ -optr h HOST @host ${ login host }$ -opt q QUSERNAME @qusername ${ username to be monitored (defaults to QSYSOPR) }$ ${ sysshep.alarm_msgw.sh: monitor's a user's message queue for messages waiting }$ sysshep.alarm_msgw.ublu ${ sysshep.alarm_msgw ( @username @password @host @qusername ) }$

# Usage message
function usage { 
echo "sysshep.alarm_msgw.sh: monitor's a user's message queue for messages waiting "
echo "This shell script was autogenerated Mon Dec 12 17:31:39 MST 2016 by taylor."
echo "Usage: $0 [silent] -h -u USERNAME -p PASSWORD -h HOST -q QUSERNAME "
echo "	where"
echo "	-h		display this help message and exit 0"
echo "	-u USERNAME	login username  (required option)"
echo "	-p PASSWORD	login password  (required option)"
echo "	-h HOST	login host  (required option)"
echo "	-q QUSERNAME	username to be monitored (defaults to QSYSOPR) "
echo "---"
echo "If the keyword 'silent' appears ahead of all options, then included files will not echo and prompting is suppressed."
echo "Exit code is the result of execution, or 0 for -h or 2 if there is an error in processing options"
}

#Test if user wants silent includes
if [ "$1" == "silent" ]
then
	SILENT="-silent "
	shift
else
	SILENT=""
fi

# Process options
while getopts u:p:h:q:h the_opt
do
	case "$the_opt" in
		u)	USERNAME="$OPTARG";;
		p)	PASSWORD="$OPTARG";;
		h)	HOST="$OPTARG";;
		q)	QUSERNAME="$OPTARG";;
		h)	usage;exit 0;;
		[?])	usage;exit 2;;
	esac
done
shift `expr ${OPTIND} - 1`
if [ $# -ne 0 ]
then
	echo "Superfluous argument(s) $*"
	usage
	exit 2
fi

# Translate options to tuple assignments
if [ "${USERNAME}" != "" ]
then
	gensh_runtime_opts="${gensh_runtime_opts}string -to @username -trim \${ ${USERNAME} }$ "
else
	echo "Option -u USERNAME is a required option but is not present."
	usage
	exit 2
fi
if [ "${PASSWORD}" != "" ]
then
	gensh_runtime_opts="${gensh_runtime_opts}string -to @password -trim \${ ${PASSWORD} }$ "
else
	echo "Option -p PASSWORD is a required option but is not present."
	usage
	exit 2
fi
if [ "${HOST}" != "" ]
then
	gensh_runtime_opts="${gensh_runtime_opts}string -to @host -trim \${ ${HOST} }$ "
else
	echo "Option -h HOST is a required option but is not present."
	usage
	exit 2
fi
if [ "${QUSERNAME}" != "" ]
then
	gensh_runtime_opts="${gensh_runtime_opts}string -to @qusername -trim \${ ${QUSERNAME} }$ "
fi

# Invocation
java -jar /opt/ublu/ublu.jar ${gensh_runtime_opts} include ${SILENT}sysshep.alarm_msgw.ublu sysshep.alarm_msgw \( @username @password @host @qusername \) 
exit $?
